spring.application.name=ecommerce-api

<<<<<<< HEAD
server.port=8082
=======
server.port=8080
>>>>>>> f10664c2ee39c15f630efa84b912c48142499e80

## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/dev
spring.datasource.username=postgres
spring.datasource.password=postgres

## Default Schema
spring.flyway.schemas=shopping
spring.jpa.properties.hibernate.default_schema=shopping